LEAST_IMPORTANT_FEATURES_V2_4: list[str] = [
    "general_efficiency_t48",
    "wdi_sp_dyn_imrt_in",
    "vdem_v2x_egal",
    "vdem_v2x_partipdem",
    "vdem_v2x_partip",
    "vdem_v2x_libdem",
    "dam_cap_pcap_t48",
    "vdem_v2xdd_dd",
    "vdem_v2x_edcomp_thick",
    "groundwater_export_t48",
    "wdi_sh_sta_stnt_zs",
    "region_Middle East & North Africa",
    "vdem_v2x_execorr",
    "region23_Western Asia",
    "region23_Southern Europe",
    "region23_Northern Africa",
    "region_Sub-Saharan Africa",
    "region23_Caribbean",
    "region23_Eastern Europe",
    "region23_Eastern Africa",
    "region23_South-Eastern Asia",
    "region23_Middle Africa",
    "region23_Northern Europe",
    "region23_Western Africa",
    "region23_Southern Africa",
    "region23_South America",
    "region_Latin America & Caribbean",
    "region23_Northern America",
    "region_North America",
    "region23_Melanesia",
    "region23_Eastern Asia",
    "region23_Central Asia",
    "region23_Central America",
    "region_Europe & Central Asia",
    "region23_Western Europe",
]

LEAST_IMPORTANT_FEATURES_V2_5: list[str] = [
    "wdi_sp_pop_0014_fe_zs",
    "wdi_se_prm_nenr",
    "splag_wdi_ag_lnd_frst_k2",
    "wdi_ms_mil_xpnd_gd_zs",
    "wdi_se_enr_prsc_fm_zs",
    "wdi_sh_dyn_mort_fe",
    "decay_ged_sb_100",
    "agr_withdrawal_pct_t48",
    "region23_Southern Asia",
    "region_South Asia",
    "groundwater_export_t48",
    "wdi_sp_dyn_le00_in",
    "region_Latin America & Caribbean",
    "region23_Southern Europe",
    "region_Sub-Saharan Africa",
    "region23_South America",
    "region23_Central America",
    "region_Europe & Central Asia",
    "region23_Eastern Africa",
    "region23_Northern America",
    "region_North America",
    "region23_Middle Africa",
    "region_Middle East & North Africa",
    "region23_Eastern Asia",
    "region23_Northern Africa",
    "region23_Central Asia",
    "region23_Caribbean",
    "region23_Melanesia",
    "region23_Eastern Europe",
    "region23_Western Asia",
    "region23_Western Africa",
    "region23_Southern Africa",
    "region23_South-Eastern Asia",
    "region23_Northern Europe",
    "region23_Western Europe",
]
