python "1. add_date.py"
Rscript "2. add_ccode_to_cm_features.R"
Rscript "3. remove_meaningless.R"
Rscript "4. add_region_to_cm.R"
python "5. create_vdem_PCAs.py"
python "6. shift yearly cm_features.py"
